branches:
  only:
    - master

language: php

php: 5.5

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - touch .env
  - ./dev-kit dispatch
